version: 0.2

phases:
  pre_build:
    commands:
      - echo "[+] Installing dependencies...."
      - pip install -r requirements.txt
      - echo "[+] Running tests..."
      - python -m pytest test/ -v
      - echo "[+] Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo "[+] Build started on `date`"
      - echo "[+] Building the Docker image..."
      - docker build -t wows/service:latest .
      - docker tag mythicalmysfits/service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/wows
  post_build:
    commands:
      - echo "[+] Build completed on `date`"
      - echo "[+] Pushing the Docker image.."
      # Push the image to ECR.
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/wows/service:latest
      - echo "[+] Completed pushing Docker image. Deploying Docker image to AWS Fargate on `date`"
      - printf '[{"name":"WOWS-Service","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/wows/service:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
